---
# control
control:
  data_name: ML100K
  data_mode: user
  target_mode: implicit
  model_name: ae
  info: 1
  data_split_mode: random-2
  ar: constant-0.1
  aw: constant
  match_rate: 1
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
